### ISSUE TITLE
Mobile view limited

### ISSUE THREAD

**Issue by bahiirwa** [ablestatehq/distributa#1]
![image](https://user-images.githubusercontent.com/7713923/152904701-634e0dd2-c2b9-4c17-bbec-1753718d7f39.png)

![image](https://user-images.githubusercontent.com/7713923/152904754-2603c69f-ca38-438b-8716-a90164323be3.png)

The mobile view makes it hard to work. See screenshots

**Comment by davidofug** [comment]
Sorry, my bad.
Didn't test it.
Let me get sometime for it today.

**Comment by davidofug** [comment]
Much improved
