### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'replace') when running project locally

### ISSUE THREAD

**Issue by tumutech** [ablestatehq/distributa#43]
Followed the steps in the ReadMe upto the point of generating the environments.txt, but when i run npm start, i get the  error in the attached screenshot, 
I'm suspecting the configuration  here to be cause of the issue:

PROJECT_ENDPOINT="https://cloud.appwrite.io/v1"
REDIRECT_URL="http://localhost:3000
 
I'm running the application locally.
 I need some help regarding the values to use for the above configuration to enable it run smoothly on local host. 
@davidofug 

![appwrite issue](https://github.com/user-attachments/assets/9258e3d7-a571-467c-bf72-a575277b7eb7)

**Comment by ANYURU** [comment]
Hey @tumutech, 
You missed the command in step 5. It is the one that generates the script environments.txt file. 
You have the command below so that you can it can create the project for you
```js
node appwrite-init.js
```
Let me know if that helped you. 
I'll update the command in the readme.

**Comment by ANYURU** [comment]
After running the command above you have to a .env file at the root of the project and copy the information in the environments.txt file to the .env file. 
```js
npm run start
```
Then at this stage the command above should get the project up and running. 
Let me know if that addresses your issue.

**Comment by tumutech** [comment]
Hey @ANYURU , 
I have followed the above procedures and it worked fine, Thank you.

**Comment by ANYURU** [comment]
You're welcome @tumutech
